[workspace]
members = ["crates/*"]
resolver = "2"

[profile.release]
lto = true
opt-level = 3

[workspace.lints.clippy]
new_without_default = "allow"

[workspace.dependencies]
# ruxy = { path = "crates/ruxy" }
