edition = "2024"
tab_spaces = 2
max_width = 120
use_small_heuristics = "Max"
reorder_imports = true
# Enable when shipped in stable:
# group_imports = "StdExternalCrate"
# imports_granularity = "Module"
