[package]
name = "sand"
description = "Playground application used for local development of Ruxy"
version = "0.1.0"
edition = "2024"

build = ".ruxy/build.rs"

[[bin]]
name = "sand"
path = ".ruxy/main.rs"

[dependencies]
ruxy = { path = "../ruxy" }

# Testing (remove when done):
hyper = "1.6.0"

[build-dependencies]
ruxy = { path = "../ruxy" }

[lints]
workspace = true