[package]
name = "sand"
version = "0.1.0"
edition = "2024"
description = "Playground application used for local development of Ruxy"

[[bin]]
name = "sand"
path = "src/app.rs"

[dependencies]
ruxy = { path = "../ruxy" }

[lints]
workspace = true
