[package]
name = "ruxy_cli"
version = "0.1.0"
edition = "2024"

[dependencies]
ruxy_routing = { path = "../routing" }
ruxy_compiler = { path = "../compiler" }

clap = { version = "4.5.38", features = ["derive"] }
inquire = { version = "0.7.5" }

[lints]
workspace = true
