[package]
name = "ruxy_config"
version = "0.1.0"
edition = "2024"

[dependencies]
ruxy_util = { path = "../util" }

tokio.workspace = true
quote.workspace = true
proc-macro2.workspace = true

[lints]
workspace = true
