[package]
name = "ruxy_routing"
version = "0.1.0"
edition = "2024"

[dependencies]
ruxy_config = { path = "../config" }
ruxy_util = { path = "../util" }

proc-macro2 = "1.0.95"
quote = "1.0.40"

[lints]
workspace = true
